url: ''
baseurl: ''
title: DPlugins Documentation
collections:
  plugins:
    output: true
    permalink: /plugins/:path/
defaults:
  - 
    scope:
      path: ""
      type: "plugins"
    values:
      layout: "plugins"
  - 
    scope:
      path: "_plugins/*/advanced"
      type: "plugins"
    values:
      category: "advanced"
  - 
    scope:
      path: "_plugins/*/{{dir}}"
      type: "plugins"
    values:
      category: "{{dir}}"