url: ''
baseurl: ''
title: DPlugins Documentation
collections:
  plugins:
    output: true
    permalink: /plugins/:path/
defaults:
  - 
    scope:
      path: ""
      type: "plugins"
    values:
      layout: "plugins"
  - 
    scope:
      path: "_plugins/*/guides"
      type: "plugins"
    values:
      category: "guides"
  - 
    scope:
      path: "_plugins/*/advanced"
      type: "plugins"
    values:
      category: "advanced"
  - 
    scope:
      path: "_plugins/*/{{dir}}"
      type: "plugins"
    values:
      category: "{{dir}}"

categories-order:
 - guides
 - advanced

algolia:
   application_id: YF7ULZ0QZ9
   index_name: test
   search_only_api_key: dad4a7fd3b85c430b6e1f865ef04a8bd
