url: ''
baseurl: ''
title: DPlugins Documentation
collections:
  plugins:
    output: true
    permalink: /plugins/:path/
defaults:
  - 
    scope:
      path: ""
      type: "plugins"
    values:
      layout: "plugins"
      toc: true
      order: "10"
      body_class: "plugins"
  - 
    scope:
      path: "_plugins/*/getting-started"
      type: "plugins"
    values:
      category: "Getting Started"
  - 
    scope:
      path: "_plugins/*/basics"
      type: "plugins"
    values:
      category: "Basics"
  - 
    scope:
      path: "_plugins/*/guides"
      type: "plugins"
    values:
      category: "Guides"
  - 
    scope:
      path: "_plugins/*/advanced"
      type: "plugins"
    values:
      category: "Advanced"
  - 
    scope:
      path: "_plugins/*/tutorials"
      type: "plugins"
    values:
      category: "Tutorials"
  - 
    scope:
      path: "_plugins/*/integrations"
      type: "plugins"
    values:
      category: "Integrations"

category_order:
  - getting-started
  - basics
  - guides
  - advanced
  - integrations
  - tutorials
  - faq

algolia:
   application_id: YF7ULZ0QZ9
   index_name: test
   search_only_api_key: dad4a7fd3b85c430b6e1f865ef04a8bd

plugins:
  - "jekyll-github-metadata"   