url: ''
baseurl: ''
title: DPlugins Documentation
collections:
  plugins:
    output: true
defaults:
  - scope:
      path: ""
      type: "plugins"
    values:
      layout: "plugins"
  - scope:
      path: "plugins/plugin-1"
      type: "plugins"
    values:
      category: marko
