backend:
  name: git-gateway
  branch: main
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
collections:
  - label: "Plugins"
    name: "plugins"
    folder: "content/blog/{{tag}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - { label: 'Blog post content', name: 'body', widget: 'markdown' }
      - { tags: ["basic", "advanced", "right"]}
